_target_: "havcocap_new.data.datasets.compressed_video.dataset_charades.CharadesCaptioningDataset"

video_root: "dataset/Charades/Charades_filtered_240"
metadata: "dataset/Charades/charades_filter_captioning.json"

video_reader: "read_frames_compressed_domain"
max_frames: 16
video_size:
  - 224
  - 224
max_words: 77
unfold_sentences: True
cv_config:
  num_gop: 16
  num_mv: 59
  num_res: 59
  with_residual: True
  use_pre_extract: False
  sample: "rand"
